##  Foundations for efficiencies

In this chapter, you'll learn what it means to write efficient Python code. You'll explore Python's Standard Library, learn about NumPy arrays, and practice using some of Python's built-in tools. This chapter builds a foundation for the concepts covered ahead.

    Welcome!    50 xp
    Pop quiz: what is efficient    50 xp
    A taste of things to come    100 xp
    Zen of Python    35 xp
    Building with built-ins    50 xp
    Built-in practice: range()    100 xp
    Built-in practice: enumerate()    100 xp
    Built-in practice: map()    100 xp
    The power of NumPy arrays    50 xp
    Practice with NumPy arrays    100 xp
    Bringing it all together: Festivus!    100 xp


##  Timing and profiling code

In this chapter, you will learn how to gather and compare runtimes between different coding approaches. You'll practice using the line_profiler and memory_profiler packages to profile your code base and spot bottlenecks. Then, you'll put your learnings to practice by replacing these bottlenecks with efficient Python code.

    Examining runtime    50 xp
    Using %timeit: your turn!    100 xp
    Using %timeit: specifying number of runs and loops    50 xp
    Using %timeit: formal name or literal syntax    100 xp
    Using cell magic mode (%%timeit)    50 xp
    Code profiling for runtime    50 xp
    Pop quiz: steps for using %lprun    50 xp
    Using %lprun: spot bottlenecks    50 xp
    Using %lprun: fix the bottleneck    50 xp
    Code profiling for memory usage    50 xp
    Pop quiz: steps for using %mprun    50 xp
    Using %mprun: Hero BMI    50 xp
    Using %mprun: Hero BMI 2.0    50 xp
    Bringing it all together: Star Wars profiling    100 xp 
    

##  Gaining efficiencies

This chapter covers more complex efficiency tips and tricks. You'll learn a few useful built-in modules for writing efficient code and practice using set theory. You'll then learn about looping patterns in Python and how to make them more efficient.

    Efficiently combining, counting, and iterating    50 xp
    Combining Pokémon names and types    100 xp
    Counting Pokémon from a sample    100 xp
    Combinations of Pokémon    100 xp
    Set theory    50 xp
    Comparing Pokédexes    100 xp
    Searching for Pokémon    100 xp
    Gathering unique Pokémon    100 xp
    Eliminating loops    50 xp
    Gathering Pokémon without a loop    100 xp
    Pokémon totals and averages without a loop    100 xp
    Writing better loops    50 xp
    One-time calculation loop    100 xp
    Holistic conversion loop    100 xp
    Bringing it all together: Pokémon z-scores    100 xp 
    

##  Basic pandas optimizations

This chapter offers a brief introduction on how to efficiently work with pandas DataFrames. You'll learn the various options you have for iterating over a DataFrame. Then, you'll learn how to efficiently apply functions to data stored in a DataFrame.

    Intro to pandas DataFrame iteration    50 xp
    Iterating with .iterrows()    100 xp
    Run differentials with .iterrows()    100 xp
    Another iterator method: .itertuples()    50 xp
    Iterating with .itertuples()    100 xp
    Run differentials with .itertuples()    100 xp
    pandas alternative to looping    50 xp
    Analyzing baseball stats with .apply()    100 xp
    Settle a debate with .apply()    100 xp
    Optimal pandas iterating    50 xp
    Replacing .iloc with underlying arrays    100 xp
    Bringing it all together: Predict win percentage    100 xp
    Congratulations!    50 xp


## In this course, you'll learn how to write cleaner, faster, and more efficient Python code

   **.We'll explore how to time and profile your code in order to find potential bottlenecks
   ** And learn practice eliminating these bottlenecks, and other bad design patterns, using Python's standard Library, NumPy and Pandas
   
   **After completing thise course, you''ll have everything you need to start writting elegant and efficient Python code. 



**Efficient refers to code that satisfiees two key concepts. 
   **first, fast to run and small latency between execution and returningg result
   **second, allocates resources skillfully and isn't subjected to unnecessary overhead

In [26]:
# Non-Pythonic
numbers = [1, 3, 5, 7, 9]

double_numbers = []

for i in range(len(numbers)):
    double_numbers.append(numbers[i]*2)
print(double_numbers)
# *************************************************************************************************** #

    
# Pythonic
double_numbers = [x*2 for x in numbers]
print(double_numbers)

[2, 6, 10, 14, 18]
[2, 6, 10, 14, 18]


## Things you should know:


   **Data types typically used in Data Science**
      Data Types for Data Science
   
   **Writing and using your own functions**
      Python Data Science Toolbox(part 1)
   
   **Anonymous functions(lambda expressions)**
      Python Data Science Toolbox(part 1)
      
   **Writing and using list comprehensions**
      Python Data Science Toolbox(part 2)

## A taste of things to come

In this exercise, you'll explore both the Non-Pythonic and Pythonic ways of looping over a list.

names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

Suppose you wanted to collect the names in the above list that have six letters or more. In other programming languages, the typical approach is to create an index variable (i), use i to iterate over the list, and use an if statement to collect the names with six letters or more:

i = 0
new_list= []
while i < len(names):
    if len(names[i]) >= 6:
        new_list.append(names[i])
    i += 1

Let's explore some more Pythonic ways of doing this.
Instructions 1/3
50 XP

    1   Print the list, new_list, that was created using a Non-Pythonic approach.

    2   A more Pythonic approach would loop over the contents of names, rather than using an index variable. Print better_list.

    3   The best Pythonic way of doing this is by using list comprehension. Print best_list.

In [25]:
# Print the list created using the Non-Pythonic approach


names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

i = 0
new_list= []
while i < len(names):
    if len(names[i]) >= 6:
        new_list.append(names[i])
    i += 1
print(new_list)

['Kramer', 'Elaine', 'George', 'Newman']


In [3]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

new_list = [i for i in names if len(i)>=6]    # I did it on the first shot
print(new_list)

['Kramer', 'Elaine', 'George', 'Newman']


In [22]:
# Print the list created by looping over the contents of names


names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

better_list = []
for name in names:
    if len(name) >= 6:
        better_list.append(name)
print(better_list)

['Kramer', 'Elaine', 'George', 'Newman']


In [24]:
# Print the list created by using list comprehension
# *************************************************************************************************** #


names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

best_list = [i for i in names if len(name) >= 6]
print(best_list)

['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']


## Zen of Python

In the video, we covered the Zen of Python written by Tim Peters, which lists 19 idioms that serve as guiding principles for any Pythonista. Python has hundreds of Python Enhancement Proposals, commonly referred to as PEPs. The Zen of Python is one of these PEPs and is documented as PEP20.

One little Easter Egg in Python is the ability to print the Zen of Python using the command import this. Let's take a look at one of the idioms listed in these guiding principles.

Type and run the command import this within your IPython console and answer the following question:

What is the 7th idiom of the Zen of Python?
Instructions
50 XP
Possible Answers

    Flat is better than nested.
    Beautiful is better than ugly.
#   Readability counts.
    Python is the best programming language ever.



## Building with built-ins


 **Built-in components are referred to as the Python Standard Library

   built-in types: list, tuple, set, dict
    
   built-in functions: print(), len(), range(), round(), enumerate(), map(), zip()
    
   built-in modules: os, sys, intertools, collections, math
    
    

In [21]:
# Buildin function: range()
   # The range() function returns a range object, 
   # which we can convert into a list
   # range() can also accept a start, stop, step value
# *************************************************************************************************** #


num_list = list(range(1,11))
n_list = range(1,25,3)

?n_list
print(num_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Type:        range
String form: range(1, 25, 3)
Length:      8
Docstring:  
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).


In [47]:
# Buildin function: enumerate()
    # enumerate() create an index item pair for each item in the object provided
    # For example, calling enumerate on the list letters produces a sequence of indexed values
    # Similar to range(), enumerate() returns an enumerate object, can be converted into a list too
    
    # We can also specify the starting index of enumerate with the keyword argument start
# *************************************************************************************************** #


letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
n_letters = enumerate(letters)
print(n_letters)
print(*n_letters)
print([*n_letters])

new_letters = list(enumerate(letters))
print(new_letters)

nn_letters = list(enumerate(letters, start=2))
print(nn_letters)

(0, 'a') (1, 'b') (2, 'c') (3, 'd') (4, 'e') (5, 'f') (6, 'g')
[]
[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd'), (4, 'e'), (5, 'f'), (6, 'g')]
[(2, 'a'), (3, 'b'), (4, 'c'), (5, 'd'), (6, 'e'), (7, 'f'), (8, 'g')]


In [91]:
# Buildin function: map()
    # The last buildin function we'll cover is map()
    # map() applies function into each element in an object
    
    # map() can also be used with lambda, or anonymous function
    # The map() function provides a quick and clean way to apply a function to an object iteratively
# *************************************************************************************************** #


nums = [1.5, 2.3, 3.4, 4.6, 5.0]

rnd_nums = map(round, nums)
print(list(rnd_nums))

surd_nums = map(lambda x: x**2, nums)
# *************************************************************************************************** #
print(list(surd_nums))
print([*surd_nums])   # My guessing is nested function caused * unpacking failure ******************* #
print(*map(lambda x: x**2, nums))
print([*map(lambda x: x**2, nums)])
# *************************************************************************************************** #
# In this tutorial, we will learn how to use the asterisk (*) operator to unpack iterable objects, 
# and two asterisks (**) to unpack dictionaries.
# *************************************************************************************************** #
nn = [*range(15)]
print(nn)

[2, 2, 3, 5, 5]
[2.25, 5.289999999999999, 11.559999999999999, 21.159999999999997, 25.0]
[]
2.25 5.289999999999999 11.559999999999999 21.159999999999997 25.0
[2.25, 5.289999999999999, 11.559999999999999, 21.159999999999997, 25.0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


## Packing With the * Operator

The * operator is known, in this context, as the tuple (or iterable) unpacking operator. It extends the unpacking functionality to allow us to collect or pack multiple values in a single variable. In the following example, we pack a tuple of values into a single variable by using the * operator:

>>> *a, = 1, 2
>>> a
[1, 2]

For this code to work, the left side of the assignment must be a tuple (or a list). That's why we use a trailing comma. This tuple can contain as many variables as we need. However, it can only contain one starred expression.

In [90]:
# We can also use the * operator to pack multiple values into a single variable. 

[*names] = 'Joh', 'Jho', 'Jo'
print(names)

[*nums] = [1.5, 2.3, 3.4, 4.6, 5.0]
print(nums)


num_dict = {'a': 1, 'b': 2, 'c': 3}
num_dict_2 = {'d': 4, 'e': 5, 'f': 6}
#n_dict = [**num_dict]
n_dict = {**num_dict}
print(n_dict)

new_dict = {**num_dict, **num_dict_2}
print(new_dict)

['Joh', 'Jho', 'Jo']
[1.5, 2.3, 3.4, 4.6, 5.0]
{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}


## Built-in practice: range()

In this exercise, you will practice using Python's built-in function range(). Remember that you can use range() in a few different ways:

1) Create a sequence of numbers from 0 to a stop value (which is exclusive). This is useful when you want to create a simple sequence of numbers starting at zero:

range(stop)

# Example
list(range(11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

2) Create a sequence of numbers from a start value to a stop value (which is exclusive) with a step size. This is useful when you want to create a sequence of numbers that increments by some value other than one. For example, a list of even numbers:

range(start, stop, step)

# Example
list(range(2,11,2))

[2, 4, 6, 8, 10]

Instructions
100 XP

    Create a range object that starts at zero and ends at five. Only use a stop argument.
    Convert the nums variable into a list called nums_list.
    Create a new list called nums_list2 that starts at one, ends at eleven, and increments by two by 
# unpacking a range object using the star character (*).

Hint

    The stop argument in range() is exclusive. This means range(11) will create a range object from zero to ten.
    To convert an object y into a list, you can use the command list(y).
    You can unpack an object z into a list by using the command [*z].


In [92]:
# Create a range object that goes from 0 to 5
nums = range(6)
print(type(nums))
print(*nums)  # My guessing is nested function caused * unpacking failure *************************** #
# *************************************************************************************************** #

# Convert nums to a list
nums_list = list(nums)
print(nums_list)

# Create a new list of odd numbers from 1 to 11 by unpacking a range object
nums_list2 = [*range(1,12,2)]
# *************************************************************************************************** #
print(nums_list2)

<class 'range'>
0 1 2 3 4 5
[0, 1, 2, 3, 4, 5]
[1, 3, 5, 7, 9, 11]


## Built-in practice: enumerate()

In this exercise, you'll practice using Python's built-in function enumerate(). This function is useful for obtaining an indexed list. For example, suppose you had a list of people that arrived at a party you are hosting. The list is ordered by arrival (Jerry was the first to arrive, followed by Kramer, etc.):

names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

If you wanted to attach an index representing a person's arrival order, you could use the following for loop:

indexed_names = []
for i in range(len(names)):
    index_name = (i, names[i])
    indexed_names.append(index_name)

[(0,'Jerry'),(1,'Kramer'),(2,'Elaine'),(3,'George'),(4,'Newman')]

But, that's not the most efficient solution. Let's explore how to use enumerate() to make this more efficient.
Instructions
100 XP

    Instead of using for i in range(len(names)), update the for loop to use i as the index variable and name as the iterator variable and use enumerate().
    Rewrite the previous for loop using enumerate() and list comprehension to create a new list, indexed_names_comp.
    Create another list (indexed_names_unpack) by using the star character (*) to unpack the enumerate object created from using enumerate() on names. This time, start the index for enumerate() at one instead of zero.

Hint

    When using enumerate() in a for loop, the first variable is an index variable. The second variable is the iterator variable.
    Use i as the index variable and name as the iterator variable in your list comprehension.
    To unpack an enumerate object, use a star character (*) before the enumerate() function.
    enumerate(names, s) will specify s as a starting index.


In [37]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

# Rewrite the for loop to use enumerate
indexed_names = []
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i,name) for i,name in enumerate(names)]
print(indexed_names_comp)

# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [enumerate(names, start=1)]
print(indexed_names_unpack)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]


In [53]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

# Rewrite the for loop to use enumerate
indexed_names = []
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i,name) for i,name in enumerate(names)]
print(indexed_names_comp)

# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [*enumerate(names, 1)]
# *************************************************************************************************** #
print(indexed_names_unpack)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


## Built-in practice: map()

In this exercise, you'll practice using Python's built-in map() function to apply a function to every element of an object. Let's look at a list of party guests:

names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

Suppose you wanted to create a new list (called names_uppercase) that converted all the letters in each name to uppercase. you could accomplish this with the below for loop:

names_uppercase = []

for name in names:
  names_uppercase.append(name.upper())

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']

Let's explore using the map() function to do this more efficiently in one line of code.
Instructions
100 XP

    Use map() and the method str.upper() to convert each name in the list names to uppercase. Save this to the variable names_map.
    Print the data type of names_map.
# *****************************************************************************************************
#    Unpack the contents of names_map into a list called names_uppercase using the star character (*).
    Print names_uppercase and observe its contents.


In [4]:
names = ['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


# Use map to apply str.upper to each element in names
names_map  = map(str.upper, names)

# Print the type of the names_map
print(type(names_map))

# Unpack names_map into a list
names_uppercase = [*names_map]
#names_uppercase = list(names_map)   # Working code

# Print the list created above
print(names_uppercase)

<class 'map'>
['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


## The power of NumPy arrays




**NumPy or Numerical Python, is an invaluable package for DataScientists.  Its the fundamental package for scientific computing in Python and pvovides a number of benefits for writing efficient code.  In this course, we'll highlight one of the most imprtant advantages of NumPy, the NumPy array.  

# NumPy arrays provides a fast and menory efficient alternative to Pytho lists.  NumPy arrays are homogeneous, which means that they must contanin elements of the same type.  

**We can see the type of each element using the .dtype() method.  




In [16]:
import numpy as np

weight = [65.4, 59.2, 63.6, 88.4, 68.7]
np_weight = np.array(weight)

np_weight.dtype
#print(dir(np_weight))


# *****************************************************************************************************
# Shape is a so-called attribute of the np2d array, that can give you more information about 
# what the data structure looks like.  Note that the syntax for access an attribute looks 
# a bit like calling a method, but they are not the same.  Remember that the method has 
# round brackets fater them and you can see here, the attribute do not.  


dtype('float64')

# *****************************************************************************************************
# Shape is a so-called attribute of the np2d array, that can give you more information about what the data structure looks like.  Note that the syntax for access an attribute looks a bit like calling a method, but they are not the same.  Remember that the method has round brackets fater them and you can see here, the attribute do not.  


In [18]:
height = [57.36, 65, 67.18, True, 70]

np_height = np.array(height)
np_height

array([57.36, 65.  , 67.18,  1.  , 70.  ])

# **In above array, the integer and boolean are preceeding dot in the array, that because NumPy converts the integer and boolean to float to retain that array's homogeneous nature.  

# Homogeneity allows NumPy array to be more memory efficient and faster than Python lists.  
**Requiring all elements be the same type eliminates the overhead needed for data type checking.  



# **When analyzing data, you often want to perform operations over entire collections of values quickly. 

**# The second advantage of NumPy arrays is they broadcasting functionality.  NumPy arrays vectorize operations, so they are performed on all elements of an object at once.  Allows us to efficiently perform calculations over entire array.  


**# Another advantange of NumPy arrays is their indexing capabilities.  When comparing basic indexing between a one-dimensional array and list, the capabilities are indentical.  

**When using two-dimensional arrays and lists, the advantages oa arrays are clear, the analogous list ayntax is a bit more verbose as you have to surround both indexing with square brackets.  

**If we select all rows and last column of our 2 dimensional array, we can use colon to represent all rows and then index -1 to represent last column.  But list dont support this kind of syntax, so we must use a list comprehension to return columns. 



In [36]:
height = [57.36, 65, 67.18, True, 70]

np_height = np.array(height)
np_height_squd = np_height**2

np_height_squd

array([3.2901696e+03, 4.2250000e+03, 4.5131524e+03, 1.0000000e+00,
       4.9000000e+03])

In [42]:
nums = [[1, 2, 3, 4], 
        [5, 6, 7, 8]]

np_nums = np.array(nums)

print(nums[0][-1])

print(np_nums[0, -1])

print([i[-1] for i in nums])
print(nums[0])

print(np_nums[:, -1])

4
4
[4, 8]
[1, 2, 3, 4]
[4 8]



**NumPy array also have a special technique called boolean indexing, with an array, we cna create a boolean mast using a simple inequality.  Indexing the array is as simple as enclosing this inequality in square brackets.  





In [51]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

np_weight = np.array(weight)


print(np_weight>66)

print(np_weight[np_weight>66])

[False False False  True  True]
[88.4 68.7]


In [82]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]


# *************************************************************************************************** #
# *************************************************************************************************** #
select_weight = [True if i>66 else False for i in weight]
print(select_weight)

# *************************************************************************************************** #
# *************************************************************************************************** #
sel_weight = [i for i in weight if i>66 ]
print(sel_weight)

[False, False, False, True, True]
[88.4, 68.7]


## Practice with NumPy arrays

# Let's practice slicing numpy arrays and using NumPy's broadcasting concept. Remember, broadcasting refers to a numpy array's ability to vectorize operations, so they are performed on all elements of an object at once.

A two-dimensional numpy array has been loaded into your session (called nums) and printed into the console for your convenience. numpy has been imported into your session as np.
Instructions 1/2
50 XP

    1
    2

    Print the second row of nums.
    Print the items of nums that are greater than six.
    Create nums_dbl that doubles each number in nums.
    Replace the third column in nums with a new column that adds 1 to each item in the original column.

Question

When compared to a list object, what are two advantages of using a numpy array?
Possible Answers

    A numpy array is the only data structure that can be used with the numpy package and often has less verbose indexing syntax.
    A numpy array contains homogeneous data types (which reduces memory consumption) and provides the ability to apply operations on all elements through broadcasting.
    A numpy array supports boolean indexing and has much better one-dimensional indexing capabilities.
    Both a list object and a numpy array are identical.

In [84]:
nums = [[1, 2, 3, 4, 5], 
        [6, 7, 8, 9, 10]]
nums = np.array(nums)

# Print second row of nums
print(nums)
print(nums[1,:])

# Print all elements of nums that are greater than six
print(nums[nums > 6])

# Double every element of nums
nums_dbl = nums * 2
print(nums_dbl)

# Replace the third column of nums
nums[:,2] = nums[:,2] + 1
print(nums)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 6  7  8  9 10]
[ 7  8  9 10]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[[ 1  2  4  4  5]
 [ 6  7  9  9 10]]


## Bringing it all together: Festivus!

In this exercise, you will be throwing a party—a Festivus if you will!

You have a list of guests (the names list). Each guest, for whatever reason, has decided to show up to the party in 10-minute increments. For example, Jerry shows up to Festivus 10 minutes into the party's start time, Kramer shows up 20 minutes into the party, and so on and so forth.

We want to write a few simple lines of code, using the built-ins we have covered, to welcome each of your guests and let them know how many minutes late they are to your party. Note that numpy has been imported into your session as np and the names list has been loaded as well.

Let's welcome your guests!
Instructions 1/4
25 XP

    1
    2
    3
    4

    Use range() to create a list of arrival times (10 through 50 incremented by 10). Create the list arrival_times by unpacking the range object.

# You can unpack the range object by placing a star character (*) in front of it; just like you've done in previous exercises.



    You realize your clock is three minutes fast. Convert the arrival_times list into a numpy array (called arrival_times_np) and use NumPy broadcasting to subtract three minutes from each arrival time.
    
    
    
#    Use list comprehension with enumerate() to pair each guest in the names list to their updated arrival time in the new_times array. You'll need to use the index variable created from using enumerate() on new_times to index the names list.




    A function named welcome_guest() has been pre-loaded into your session. Use map() to apply this function to each element of the guest_arrivals list and save it as the variable welcome_map.


In [85]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']


# Create a list of arrival times
arrival_times = [*range(10, 50, 10)]

print(arrival_times)

[10, 20, 30, 40]


In [86]:
# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

print(new_times)

[ 7 17 27 37 47]


In [105]:
# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]
# *************************************************************************************************** #
# *************************************************************************************************** #

print(guest_arrivals)


[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]


In [195]:
#print(help(welcome_guest))
#
#Help on function welcome_guest in module __main__:
#
#welcome_guest(guest_and_time)
#    Returns a welcome string for the guest_and_time tuple.
#    
#    Args:
#        guest_and_time (tuple): The guest and time tuple to create
#            a welcome string for.
#            
#    Returns:
#        welcome_string (str): A string welcoming the guest to Festivus.
#        'Welcome to Festivus {guest}... You're {time} min late.'
#
#None

#welcome_guest??
#Return:
def welcome_guest(guest_and_time):
    
    """\n
    Returns a welcome string for the guest_and_time tuple.\n
    
    Args:\n
      guest_and_time (tuple): The guest and time tuple to create\n
      a welcome string for.\n
      
    Returns:\n
      welcome_string (str): A string welcoming the guest to Festivus.\n
      \'Welcome to Festivus {guest}... You\'re {time} min late.\'\n    \n
    """

    guest = guest_and_time[0]
    arrival_time = guest_and_time[1]
    welcome_string = "Welcome to Festivus {}... You\'re {} min late.".format(guest,arrival_time)
    return welcome_string
#\nFile:      /tmp/tmpdqkos8y4/<ipython-input-1-286a427e45ef>\nType:      function\n'}

 
#In [9]:
#welcome_guest(guest_arrivals)
#Out[9]:
#"Welcome to Festivus ('Jerry', 7)... You're ('Kramer', 17) min late."


def welcome_guest(guest_and_time):

#    for guest, time in guest_and_time:
#        print(f"Welcome to Festivus {guest}... You've {time} min late")
# Return:
# ValueError: too many values to unpack (expected 2)
    
#    print(f"Welcome to Festivus {i.index(0) for i in guest_and_time}.\
#    ...You've {i.index(1) for i in guest_and_time} min late")

    return f"Welcome to Festivus {guest_and_time[0]}... You've {guest_and_time[1]} min late"
# It used to Return:
# Welcome to Festivus Jerry.          ...You've 7 min late

#    return f"Welcome to Festivus {[i[0] for i in guest_arrivals]}.\
#    ...You.ve {[i[1] for i in guest_arrivals]} min late"
# Return:
# Welcome to Festivus ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman'].    ...You.ve [7, 17, 27
              

# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

# Map the welcome_guest function to each (guest,time) pair
welcome_map = map(welcome_guest, guest_arrivals)
# *************************************************************************************************** #
# *************************************************************************************************** #
# map() a function on [('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]
# function will be applied on each tuple pair ('Jerry', 7), then ('Kramer', 17)


guest_welcomes = [*welcome_map]
print(*guest_welcomes, sep='\n')


Welcome to Festivus Jerry... You've 7 min late
Welcome to Festivus Kramer... You've 17 min late
Welcome to Festivus Elaine... You've 27 min late
Welcome to Festivus George... You've 37 min late
Welcome to Festivus Newman... You've 47 min late


In [147]:
print(guest_arrivals)
#print(dir(guest_arrivals))

print(guest_arrivals[0][0])

print([i[0] for i in guest_arrivals])

[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]
Jerry
['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']


In [102]:
def welcome_guest(guest_and_time):
    #for guest, time in guest_and_time:
    #print(f"Welcome to Festivus {guest_and_time[:, 0]}... You've {guest_and_time[:, 1]} min late")

    for guest, time in guest_and_time:
        print(f"Welcome to Festivus {guest}... You've {time} min late")
        
        
welcome_guest(guest_arrivals)

Welcome to Festivus Jerry... You've 7 min late
Welcome to Festivus Kramer... You've 17 min late
Welcome to Festivus Elaine... You've 27 min late
Welcome to Festivus George... You've 37 min late
Welcome to Festivus Newman... You've 47 min late


# *****************************************************************************************************

In [188]:
def welcome_guest(guest_and_time):
    return f"Welcome to Festivus {guest_and_time[0]} ...You've {guest_and_time[1]} min late"

out = welcome_guest(guest_arrivals)
out2 = [*[out]]

print(*out2)
print()

welcome = map(welcome_guest, guest_arrivals)
to_print = [*welcome]
print(to_print)
print()
print(*to_print, sep='\n')

# *************************************************************************************************** #
# To feel and understand the * unpacking immplementation and the map function using on iterable object

Welcome to Festivus ('Jerry', 7) ...You've ('Kramer', 17) min late

["Welcome to Festivus Jerry ...You've 7 min late", "Welcome to Festivus Kramer ...You've 17 min late", "Welcome to Festivus Elaine ...You've 27 min late", "Welcome to Festivus George ...You've 37 min late", "Welcome to Festivus Newman ...You've 47 min late"]

Welcome to Festivus Jerry ...You've 7 min late
Welcome to Festivus Kramer ...You've 17 min late
Welcome to Festivus Elaine ...You've 27 min late
Welcome to Festivus George ...You've 37 min late
Welcome to Festivus Newman ...You've 47 min late


## Examining runtime








